### ISSUE TITLE
Fail to send 

### ISSUE THREAD

**Issue by sergedenni** [yuri-rage/ESP-Now-Serial-Bridge#1]
Hi, 
Tank's for thins project i think it's what i searching for but i have put the both mac adress an cant send only send fail 
is it other ton configure ? on one ESP32 BORD1 the Other ESP32 is BOARD2

**Comment by yuri-rage** [comment]
You must put the MAC address for BOARD2 in line 45, and the MAC address for BOARD1 in line 50.

When you upload to BOARD1, leave line 42 as `#define BOARD1`.

When you upload to BOARD2, change line 42 to `#define BOARD2`.

I know it's confusing.  I couldn't think of a better way to write that.

**Comment by sergedenni** [comment]
Thank's it works fine :)
