### ISSUE TITLE
Bidirectional RS485 possible?

### ISSUE THREAD

**Issue by sergedenni** [yuri-rage/ESP-Now-Serial-Bridge#2]
Hi is it possible to read and send (bidirectionnal) to serial1 (gpio16 17)
I explain what i want to do 
Device Tx/Rx RS485 infos > RS485 TTL Modul > ESP32 > ESP Now Serial Bridge Transmitting over the Air > ESP32 > RS485 TTL modul Tx/Rx to device.
Is it possible ? ....... can you Help me ? :))))

**Comment by yuri-rage** [comment]
I think this should be possible, but I do not have hardware on hand to test it.  You should be able to define the UART pins on lines 58 and 59 and then leave line 63 commented so that `Serial.print` statements are ignored (or modify the sketch to print debug statements to UART0).

**Comment by sergedenni** [comment]
i have test  rs485TTL modul wired rx tx rs485TTL > ok work 
i have test on ESP32 pin 1- 3 for rx tx with or without debug > nothing (debug work see the link)
i have test on pin 16 17 without or with debug seem nothing send ton Board2 ( i have activate send and recieve blink (work on board1 but  nothing on board2)) ( on board 1 serial monitor send fail message ) (on board2 nothing)
i need ton send infos from board1 and recieve infos from board2 to board1
please it's a very important project for me

**Comment by sergedenni** [comment]
It Works :))))))
I use on eatch ESP32 Rx GPIO 16 Pin and Tx GPIO1 Pin and I have a bidirectional communication It works perfect
