### ISSUE TITLE
Tested with esp8266? 

### ISSUE THREAD

**Issue by cent0** [yuri-rage/ESP-Now-Serial-Bridge#4]
Hello sir
The code work for esp8266
With speed 9600 baud is possible increasing buffer to 350/400
Thank you

**Comment by JKuav** [comment]
I think its not possible because the payload size is limited by esp32

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_now.html

**Comment by yuri-rage** [comment]
I have another project that overcomes payload limits:
https://github.com/yuri-rage/ESP-Now-Burst-Serial-Bridge
